name: Build
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Fast APT Mirror
      uses: vegardit/fast-apt-mirror.sh@v1
      with: # the following parameters are listed with their action default values and are optional
        healthchecks:  20 # Number of mirrors from the mirrors list to check for availability and up-to-dateness
        speedtests:    10 # Maximum number of healthy mirrors to test for speed
        parallel:       2 # Number of parallel speed tests
        sample-size: 1024 # Number of kilobytes to download during the speed from each mirror
        sample-time:    3 # Maximum number of seconds within the sample download from a mirror must finish
